[environment]
cpu_count = 12
exec_env = "singularity"
free_mem = 183.7
overcommit_policy = "heuristic"
overcommit_limit = "50%"
nipype_version = "1.7.0"
templateflow_version = "0.7.2"
version = "20.2.7"

[execution]
bids_dir = "/cubric/collab/487_mvpa/poppy-effex/dataset/bids"
bids_database_dir = "/cubric/collab/487_mvpa/poppy-effex/dataset/proc/pybids/bids_db/fmriprep-20.2.7"
boilerplate_only = false
sloppy = false
debug = []
fmriprep_dir = "/cubric/collab/487_mvpa/poppy-effex/dataset/derivatives/fmriprep/20.2.7/output/fmriprep"
fs_license_file = "/home/saptaf1/freesurfer_license.txt"
fs_subjects_dir = "/cubric/collab/487_mvpa/poppy-effex/dataset/derivatives/freesurfer/6.0.1/output/ses-1"
layout = "BIDS Layout: ..._mvpa/poppy-effex/dataset/bids | Subjects: 1 | Sessions: 1 | Runs: 0"
log_dir = "/cubric/collab/487_mvpa/poppy-effex/dataset/derivatives/fmriprep/20.2.7/output/fmriprep/logs"
log_level = 20
low_mem = false
md_only_boilerplate = false
notrack = true
output_dir = "/cubric/collab/487_mvpa/poppy-effex/dataset/derivatives/fmriprep/20.2.7/output"
output_layout = "legacy"
output_spaces = "MNI152NLin2009cAsym:res-native"
reports_only = false
run_uuid = "20240807-173548_bd1d274f-f30d-4331-978c-0058be4f4909"
participant_label = [ "126BPCP021001",]
templateflow_home = "/cubric/collab/487_mvpa/poppy-effex/templateflow"
work_dir = "/cubric/collab/487_mvpa/poppy-effex/dataset/derivatives/fmriprep/20.2.7/work/fmriprep-20.2.7"
write_graph = true

[workflow]
anat_only = false
aroma_err_on_warn = false
aroma_melodic_dim = -200
bold2t1w_dof = 6
bold2t1w_init = "register"
cifti_output = false
fmap_bspline = false
force_syn = false
hires = true
ignore = []
longitudinal = false
medial_surface_nan = false
regressors_all_comps = true
regressors_dvars_th = 1.5
regressors_fd_th = 0.5
run_reconall = true
skull_strip_fixed_seed = false
skull_strip_template = "OASIS30ANTs"
skull_strip_t1w = "force"
slice_time_ref = 0.5
use_aroma = false
use_syn_sdc = false

[nipype]
crashfile_format = "txt"
get_linked_libs = false
memory_gb = 180
nprocs = 12
omp_nthreads = 4
plugin = "MultiProc"
resource_monitor = false
stop_on_first_crash = false

[seeds]
master = 15530
ants = 33121
numpy = 26078

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
